name: flutter_social_media_ui
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.1
  http: ^1.2.2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  shimmer: ^3.0.0
  chewie: ^1.8.5
  video_player:
  intl:
  extended_image: ^9.0.4
  flutter_launcher_icons: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/icon/
    - assets/placeholder.png
